<?php
$myaddons = array();
$maNum = 0;
$myaddons[$maNum] = array('65', '/uploads/allimg/150519/1-150519195A9621.jpg');
$maNum = 1;
$myaddons[$maNum] = array('66', '/uploads/allimg/150519/1-150519195R5131.jpg');
$maNum = 2;
$myaddons[$maNum] = array('67', '/uploads/allimg/150519/1-15051920001H29.jpg');
$maNum = 3;
$myaddons[$maNum] = array('68', '/uploads/allimg/150519/1-150519200052M7.jpg');
$maNum = 4;
$myaddons[$maNum] = array('69', '/uploads/allimg/150519/1-15051920014OG.jpg');
$maNum = 5;
$myaddons[$maNum] = array('70', '/uploads/allimg/150519/1-150519200215620.png');
$maNum = 6;
