<?php
$myaddons = array();
$maNum = 0;
$myaddons[$maNum] = array('57', '/uploads/allimg/150519/1-1505191F025450.jpg');
$maNum = 1;
$myaddons[$maNum] = array('58', '/uploads/allimg/150519/1-1505191F052128.jpg');
$maNum = 2;
$myaddons[$maNum] = array('59', '/uploads/allimg/150519/1-1505191F111b5.jpg');
$maNum = 3;
$myaddons[$maNum] = array('60', '/uploads/allimg/150519/1-1505191F129203.jpg');
$maNum = 4;
