<?php
$myaddons = array();
$maNum = 0;
$myaddons[$maNum] = array('61', '/uploads/allimg/150519/1-1505191HGS56.jpg');
$maNum = 1;
$myaddons[$maNum] = array('62', '/uploads/allimg/150519/1-1505191I02N93.jpg');
$maNum = 2;
$myaddons[$maNum] = array('63', '/uploads/allimg/150519/1-1505191IAO63.jpg');
$maNum = 3;
$myaddons[$maNum] = array('64', '/uploads/allimg/150519/1-1505191K524526.jpg');
$maNum = 4;
