<?php
$typeArr[1] = '公司简介';
$typeArr[2] = '公司简介';
$typeArr[19] = '妇科知识';
$typeArr[3] = '质量管理';
$typeArr[4] = '经营理念';
$typeArr[5] = '企业资质';
$typeArr[6] = '研发中心';
$typeArr[7] = '新闻资讯';
$typeArr[32] = '产品介绍';
$typeArr[10] = '联系我们';
$typeArr[12] = '行业动态';
$typeArr[13] = '公司新闻';
$typeArr[14] = '联系我们';
$typeArr[15] = '友情链接';
$typeArr[17] = '法律声明';
$typeArr[18] = '网站地图';
$typeArr[21] = '检测中心';
$typeArr[23] = '研发中心';
$typeArr[25] = '妇科炎症';
$typeArr[26] = '宫颈糜烂';
$typeArr[27] = '阴道炎';
$typeArr[28] = '阴道紧缩';
$typeArr[29] = '月经不调';
?>