	
<field:company itemname="公司名称" autofield="1" type="text" isnull="true" default=""  maxlength="36" issearch="" isshow="" state="1">	
</field:company>	
	
<field:product itemname="公司产品" autofield="1" type="text" isnull="true" default=""  maxlength="50" issearch="" isshow="" state="1">	
</field:product>	
	
<field:place itemname="所在地址" autofield="1" type="int" isnull="true" default="0"  maxlength="5" issearch="" isshow="" state="1">	
</field:place>	
	
<field:vocation itemname="所属行业" autofield="1" type="int" isnull="true" default="0"  maxlength="5" issearch="" isshow="" state="1">	
</field:vocation>	
	
<field:cosize itemname="公司规模" autofield="1" type="int" isnull="true" default="0"  maxlength="5" issearch="" isshow="" state="1">	
</field:cosize>	
	
<field:tel itemname="电话号码" autofield="1" type="text" isnull="true" default=""  maxlength="30" issearch="" isshow="" state="1">	
</field:tel>	
	
<field:fax itemname="传真" autofield="1" type="text" isnull="true" default=""  maxlength="30" issearch="" isshow="" state="1">	
</field:fax>	
	
<field:linkman itemname="联系人" autofield="1" type="text" isnull="true" default=""  maxlength="20" issearch="" isshow="" state="1">	
</field:linkman>	
	
<field:address itemname="详细地址" autofield="1" type="text" isnull="true" default=""  maxlength="50" issearch="" isshow="" state="1">	
</field:address>	
	
<field:mobile itemname="手机" autofield="1" type="text" isnull="true" default=""  maxlength="30" issearch="" isshow="" state="1">	
</field:mobile>	
	
<field:email itemname="邮箱" autofield="1" type="text" isnull="true" default=""  maxlength="50" issearch="" isshow="" state="1">	
</field:email>	
	
<field:url itemname="地址" autofield="1" type="text" isnull="true" default=""  maxlength="50" issearch="" isshow="" state="1">	
</field:url>	
	
<field:uptime itemname="更新时间" autofield="1" type="int" isnull="true" default="0"  maxlength="10" issearch="" isshow="" state="1">	
</field:uptime>	
	
<field:checked itemname="是否审核" autofield="1" type="int" isnull="true" default="0"  maxlength="1" issearch="" isshow="" state="1">	
</field:checked>	
	
<field:introduce itemname="公司简介" autofield="1" type="multitext" isnull="true" default=""  maxlength="250" issearch="" isshow="" state="1">	
</field:introduce>	
	
<field:comface itemname="公司标志" autofield="1" type="text" isnull="true" default=""  maxlength="255" issearch="" isshow="" state="1">	
</field:comface>	
