<?php
$z[0]=Array("global","",242,270);
$z[0][4]['name']="cfg_soft_lang";
$z[1]=Array("field","",283,302);
$z[1][4]['name']="title";
$z[2]=Array("global","",303,329);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("field","",370,399);
$z[3][4]['name']="keywords";
$z[4]=Array("field","",439,497);
$z[4][4]['name']="description";
$z[4][4]['function']="html2text(@me)";
$z[5]=Array("global","",519,551);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("global","",619,651);
$z[6][4]['name']="cfg_templets_skin";
$z[7]=Array("include","",939,974);
$z[7][4]['filename']="head.htm";
$z[8]=Array("global","",1136,1168);
$z[8][4]['name']="cfg_templets_skin";
$z[9]=Array("channel","\r\n                    <li><a href='[field:typeurl/]'>[field:typename/]</a></li>\r\n                    ",1288,1501);
$z[9][4]['type']="son";
$z[9][4]['currentstyle']="<li class='alt'><a href='~typelink~'>~typename~</a></li>";
$z[10]=Array("global","",1654,1686);
$z[10][4]['name']="cfg_templets_skin";
$z[11]=Array("type","[field:typename /]",2343,2384);
$z[12]=Array("field","",2417,2448);
$z[12][4]['name']="typenameng";
$z[13]=Array("field","",2456,2485);
$z[13][4]['name']="position";
$z[14]=Array("field","",2641,2662);
$z[14][4]['name']="content";
$z[15]=Array("global","",2817,2849);
$z[15][4]['name']="cfg_templets_skin";
$z[16]=Array("include","",2948,2985);
$z[16][4]['filename']="footer.htm";

?>