<?php
$z[0]=Array("global","",243,271);
$z[0][4]['name']="cfg_soft_lang";
$z[1]=Array("field","",284,303);
$z[1][4]['name']="title";
$z[2]=Array("global","",304,330);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("field","",371,400);
$z[3][4]['name']="keywords";
$z[4]=Array("field","",440,498);
$z[4][4]['name']="description";
$z[4][4]['function']="html2text(@me)";
$z[5]=Array("global","",520,552);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("global","",620,652);
$z[6][4]['name']="cfg_templets_skin";
$z[7]=Array("include","",944,979);
$z[7][4]['filename']="head.htm";
$z[8]=Array("global","",1141,1173);
$z[8][4]['name']="cfg_templets_skin";
$z[9]=Array("channel","\r\n                    <li><a href='[field:typeurl/]'>[field:typename/]</a></li>\r\n                    ",1290,1503);
$z[9][4]['type']="son";
$z[9][4]['currentstyle']="<li class='alt'><a href='~typelink~'>~typename~</a></li>";
$z[10]=Array("include","",1605,1640);
$z[10][4]['filename']="left.htm";
$z[11]=Array("type","[field:typename /]",1827,1868);
$z[12]=Array("field","",1901,1932);
$z[12][4]['name']="typenameng";
$z[13]=Array("field","",1940,1969);
$z[13][4]['name']="position";
$z[14]=Array("field","",2125,2146);
$z[14][4]['name']="content";
$z[15]=Array("global","",2301,2333);
$z[15][4]['name']="cfg_templets_skin";
$z[16]=Array("include","",2432,2469);
$z[16][4]['filename']="footer.htm";

?>