<?php
$z[0]=Array("global","",243,271);
$z[0][4]['name']="cfg_soft_lang";
$z[1]=Array("field","",284,303);
$z[1][4]['name']="title";
$z[2]=Array("global","",304,330);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("field","",371,400);
$z[3][4]['name']="keywords";
$z[4]=Array("field","",440,498);
$z[4][4]['name']="description";
$z[4][4]['function']="html2text(@me)";
$z[5]=Array("global","",520,552);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("global","",620,652);
$z[6][4]['name']="cfg_templets_skin";
$z[7]=Array("include","",940,975);
$z[7][4]['filename']="head.htm";
$z[8]=Array("global","",1137,1169);
$z[8][4]['name']="cfg_templets_skin";
$z[9]=Array("channel","\r\n                    <li><a href='[field:typeurl/]'>[field:typename/]</a></li>\r\n                    ",1283,1496);
$z[9][4]['type']="son";
$z[9][4]['currentstyle']="<li class='alt'><a href='~typelink~'>~typename~</a></li>";
$z[10]=Array("global","",1649,1681);
$z[10][4]['name']="cfg_templets_skin";
$z[11]=Array("type","[field:typename /]",2333,2374);
$z[12]=Array("field","",2407,2438);
$z[12][4]['name']="typenameng";
$z[13]=Array("field","",2446,2475);
$z[13][4]['name']="position";
$z[14]=Array("field","",2631,2652);
$z[14][4]['name']="content";
$z[15]=Array("global","",2807,2839);
$z[15][4]['name']="cfg_templets_skin";
$z[16]=Array("include","",2938,2975);
$z[16][4]['filename']="footer.htm";

?>