<?php
$z[0]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"<a href='{@me['arcurl']}' class='preview'><img src='{@me['litpic']}' class='left'/></a>\"); ",4,171);
$z[0][4]['runphp']="yes";
$z[1]=Array("arcurl","",259,274);
$z[2]=Array("title","",290,304);
$z[3]=Array("pubdate","",314,356);
$z[3][4]['function']="GetDateMK(@me)";
$z[4]=Array("description","",435,455);
$z[5]=Array("arcurl","",501,516);
$z[6]=Array("global","",578,611);
$z[6][4]['name']="cfg_templets_skin";

?>