<?php
$z[0]=Array("global","",80,105);
$z[0][4]['name']="cfg_cmsurl";
$z[1]=Array("global","",188,213);
$z[1][4]['name']="cfg_cmsurl";
$z[2]=Array("channel","\r\n      	<li><a href='[field:typeurl/]' [field:rel/]>[field:typename/]<br /><span>[field:typenameng/]</span></a></li>\r\n      	",290,613);
$z[2][4]['type']="top";
$z[2][4]['row']="10";
$z[2][4]['currentstyle']="<li class='hover'><a href='~typelink~' ~rel~ class='navnow' style='color:#F1861C'>~typename~<br /><span>~typenameng~</span></a></li>";

?>