document.writeln("<DIV id=floatTools class=float0831>");
document.writeln("<DIV class=floatL>");
document.writeln("<A style=\"DISPLAY: none\" id=aFloatTools_Show class=btnOpen title=联系在线QQ客服 onclick=\"javascript:$(\'#divFloatToolsView\').animate({width: \'show\', opacity: \'show\'}, \'normal\',function(){ $(\'#divFloatToolsView\').show();kf_setCookie(\'RightFloatShown\', 0, \'\', \'/\', \'\'); });$(\'#aFloatTools_Show\').attr(\'style\',\'display:none\');$(\'#aFloatTools_Hide\').attr(\'style\',\'display:block\');\">展开</A>");
document.writeln("<A id=aFloatTools_Hide class=btnCtn title=关闭在线QQ客服 onclick=\"javascript:$(\'#divFloatToolsView\').animate({width: \'hide\', opacity: \'hide\'}, \'normal\',function(){ $(\'#divFloatToolsView\').hide();kf_setCookie(\'RightFloatShown\', 1, \'\', \'/\', \'\'); });$(\'#aFloatTools_Show\').attr(\'style\',\'display:block\');$(\'#aFloatTools_Hide\').attr(\'style\',\'display:none\');\">收缩</A> </DIV>");
document.writeln("<DIV id=divFloatToolsView class=floatR>");
document.writeln("<DIV class=tp></DIV>");
document.writeln("<DIV class=cn>");
document.writeln("<UL>");
document.writeln("<LI class=top><H3 class=titZx>在线咨询</H3></LI>");
document.writeln("<LI><A class=icoQQ href=\"http://wpa.qq.com/msgrd?v=3&uin=244876016&site=qq&menu=yes\" target=\"_blank\">售前客服</A></LI>");
document.writeln("<LI><A class=icoQQ href=\"http://wpa.qq.com/msgrd?v=3&uin=1169293220&site=qq&menu=yes\" target=\"_blank\">业务咨询客服</A></LI>");
document.writeln("<LI><A class=icoQQ href=\"http://wpa.qq.com/msgrd?v=3&uin=244876016&site=qq&menu=yes\" target=\"_blank\">售后客服</A></LI>");
document.writeln("<LI><A class=icoWW href=\"http://amos.alicdn.com/getcid.aw?spm=a1z10.1-c.0.0.ZrUsqf&v=3&site=cntaobao&groupid=0&s=1&fromid=cntaobaoyekai58&uid=%D6%A3vivy\" target=\"_blank\">业务咨询客服</A></LI>");
document.writeln("<LI><A class=icoWW href=\"http://amos.alicdn.com/getcid.aw?spm=a1z10.1-c.0.0.ZrUsqf&v=3&site=cntaobao&groupid=0&s=1&fromid=cntaobaoyekai58&uid=%D6%A3vivy\" target=\"_blank\">业务咨询客服</A></LI>");
document.writeln("<LI><A class=icoWW href=\"http://amos.alicdn.com/getcid.aw?spm=a1z10.1-c.0.0.ZrUsqf&v=3&site=cntaobao&groupid=0&s=1&fromid=cntaobaoyekai58&uid=%D6%A3vivy\" target=\"_blank\">业务咨询客服</A></LI>");
document.writeln("<LI class=top><H3 class=titDh>电话咨询</H3></LI>");
document.writeln("<LI><A class=icoDH target=\"_blank\">400-1668-732</A></LI>");
document.writeln("<span><img src=\"\/qq1\/erweima.png\" style=\"width:100px;height:100px\"><br>扫描二维码有惊喜</span>");
document.writeln("</UL>");
document.writeln("</DIV>");
document.writeln("</DIV>");
document.writeln("</DIV>");